### ISSUE TITLE
As a user, I have a frontend site that I can see Run history for projects.

### ISSUE THREAD

**Issue by bjinwright** [MetaMetricsInc/loadlamb#8]
# End Goal
Allow stake holders and engineers to log in using credentials from a Cognito pool to view a projects history based on Run information.

## Tasks

- [ ]  **Create mockups** - Design mockups for every view (page) for the site. (Brian)
- [ ]  **Create HTML Templates** - Send PSD to HTML chopping service
- [ ]  **Create Django Project** - Go through the Django scaffolding process. (Gabriel)
- [ ]  **Create Login View** - Create Django view to login
- [ ]  **Create List Projects View** - Create Django view to list all of the projects.
- [ ]  **Create List Runs for Project View** - Create Django view to list all of Runs for a specific project
- [ ]  **Create Detail View for Run** - Create Django view that shows details about a Run including comparative stats

**Comment by bjinwright** [comment]
Complete
